---
name: Test Meta

on:
  workflow_dispatch:

jobs:
  build-image:
    name: Build Images
    runs-on: ubuntu-latest
    steps:


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

#NEW: (START) ##########################################################
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/docker-ci-automation, test-image-name
          flavor: |
            latest=false
          tags: |
            type=raw,value=testmeta
#NEW: (END) ############################################################
      
      - name: Echo tags
        run: echo ${{ steps.docker_meta.outputs.tags }}