name: Echo GitHub Ref

on:
  release:
    types: [released]

jobs:
  echo_ref:
    runs-on: ubuntu-latest

    steps:
      - name: echo ref
        run: echo "${{ github.ref }}"
      #- name: Echo GitHub Ref
      #  if: ${{ github.event_name == 'release' && github.event.release.tag_name != null }}
      #  run: echo "Newly created Git tag: ${{ github.event.release.tag_name }}"
