name: Echo GitHub Ref

on:
  release:
    types: [released]

jobs:
  echo_ref:
    runs-on: ubuntu-latest

    steps:
      - name: Echo GitHub Ref
        if: github.event_name == 'release'
        run: echo "Newly created Git tag: ${{ github.event.release.tag_name }}"
