name: Echo GitHub Ref

on:
  release:
    types: [published]

jobs:
  echo_ref:
    runs-on: ubuntu-latest

    steps:
      - name: Echo GitHub Ref
        run: echo "The value of github.ref is ${{ github.ref }}"

      - name: Echo Git Tag for Release
        if: github.event_name == 'release'
        run: echo "Git tag for the release: ${{ github.event.release.tag_name }}"
