name: Echo GitHub Ref

on:
  release:
    types: [published]

jobs:
  echo_ref:
    runs-on: ubuntu-latest

    steps:
      - name: Echo GitHub Ref
        if: github.event_name == 'release'
        run: echo '${{ toJson(github) }}' | jq .
