name: Echo GitHub Ref

on:
  release:
    types: [created, edited]

jobs:
  echo_ref:
    runs-on: ubuntu-latest

    steps:
      - name: Echo GitHub Ref
        run: echo "The value of github.ref is ${{ github.ref }}"
      - name: Echo Git Tag for Release
        run: echo "Git tag for the release: ${{ github.event.release.tag_name }}"
